# Generated by Django 3.1.7 on 2021-03-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('album', models.CharField(max_length=240, verbose_name='Album')),
                ('artist', models.CharField(max_length=100, verbose_name='Artist')),
                ('released_date', models.DateField(verbose_name='Released Date')),
                ('energy_low', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Energy_Low')),
                ('energy_med', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Energy_Medium')),
                ('energy_high', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Energy_High')),
            ],
        ),
    ]
