# Generated by Django 3.1.7 on 2021-03-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_auto_20210312_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='energy_high',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='Energy_High'),
        ),
    ]
