# Generated by Django 3.1.7 on 2021-03-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20210312_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Title')),
                ('segment', models.FileField(upload_to='music_segments/')),
            ],
        ),
    ]
